[package]
name = "wat"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serenity = "=0.12.2"
lazy_static = "1.5.0"
dotenv = "0.15.0"